Guestlogix/traveler-ios

traveler-ios-ui/TravelerKitUI/Storyboards/CatalogItem.storyboard
Just adds constraints + changes line break to word wrap
* Fixes #174 
* Connects #
=> Changes product name to word wrap + 8pts away from price

TravelerKit.podspec, TravelerKitUI.podspec, TravelerStripePaymentProvider.podspec, appcenter-post-build.sh
=> Adds Core POD

traveler-ios-ui/TravelerKitUI.xcodeproj/project.pbxproj, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormDateInputCell.swift, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormDateInputCell.xib, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormLayout.swift, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormValueDisplayInputCell.swift, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormValueDisplayInputCell.xib, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormView.swift, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/InputType.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/BookingQuestionsViewController.swift, traveler-swift-core/TravelerKit/Extensions/DateFormatter+PassengerKit.swift, traveler-swift-core/TravelerKit/Models/Answer.swift, traveler-swift-core/TravelerKit/Models/BookingForm.swift, traveler-swift-core/TravelerKit/Models/Question.swift
=> Adds date type question to the formview

traveler-ios-ui/TravelerKitUI/ViewControllers/BookingQuestionsViewController.swift, traveler-swift-core/TravelerKit/Models/BookingForm.swift
Accidentally merged in questions mock with the .date questions pull request
* Fixes #
* Connects #
=> Removes question mock

traveler-ios-ui/TravelerKitUI/Storyboards/CatalogItem.storyboard, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormView.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/ReceiptViewController.swift, traveler-swift-core/TravelerKit/AuthPath.swift, traveler-swift-core/TravelerKit/Models/Order.swift, traveler-swift-core/TravelerKit/Pineapple/MappingOperation.swift
Updates model so the user can get past the questions screen
* Fixes #
* Connects #
=> CHORE | Fixes order flow to work

traveler-ios-ui/TravelerKitUI/ViewControllers/OrderSummaryViewController.swift
Adds swipe action to remove credit card payment when paying for an order. 
* Fixes #
* Connects #
=> Adds swipe action to remove credit card payment

traveler-ios-ui/TravelerKitUI/ViewControllers/OrderResultViewController.swift
=> Updates list of orders in OrderResult VC

traveler-ios-ui/TravelerKitUI/Storyboards/Orders.storyboard
=> Removes button from cancellation screen

traveler-ios-ui/TravelerKitUI/ViewControllers/BookableProductDetailViewController.swift
=> Changes date formatter to ISO

traveler-ios-ui/TravelerKitUI.xcodeproj/project.pbxproj
=> Adds file with extension to Cancellation Error

traveler-ios-ui/TravelerKitUI/ModelExtensions/Order+TravelerUI.swift, traveler-ios-ui/TravelerKitUI/Storyboards/Orders.storyboard, traveler-ios-ui/TravelerKitUI/ViewControllers/OrderDetailViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/ReceiptViewController.swift, traveler-swift-core/TravelerKit.xcodeproj/project.pbxproj, traveler-swift-core/TravelerKit/AuthPath.swift, traveler-swift-core/TravelerKit/Delegates/EmailOrderConfirmationDelegate.swift, traveler-swift-core/TravelerKit/Delegates/EmailTicketsDelegate.swift, traveler-swift-core/TravelerKit/Models/Order.swift, traveler-swift-core/TravelerKit/Operations/AuthenticatedRemoteRequestOperation.swift, traveler-swift-core/TravelerKit/Pineapple/RemoteRequestOperation.swift, traveler-swift-core/TravelerKit/Traveler.swift
=> Adds functionality to email tickets

Traveler.xcodeproj/project.pbxproj, Traveler/AppDelegate.swift, Traveler/Environment /CI.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/BookingQuestionsViewController.swift
=> Extracts keys and adds environment variables

Traveler.xcodeproj/project.pbxproj, Traveler/AppDelegate.swift, Traveler/Environment/Environment.swift
=> Renames folder and struct to environment

Traveler/GuestAPI/GuestRoute.swift
=> Changes login endpoint

traveler-swift-core/TravelerKit/AuthPath.swift
=> Corrects path for patch request for sending emails.

Traveler copy-Info.plist, Traveler.xcodeproj/project.pbxproj, Traveler.xcodeproj/xcshareddata/xcschemes/gCrew.xcscheme
=> Adds new scheme and changes target name

Traveler/Environment/Environment.swift, Traveler/GuestAPI/GuestRoute.swift, traveler-ios-stripe/TravelerStripePaymentProvider/StripePaymentProvider.swift, traveler-swift-core/TravelerKit/TravelerRoute.swift
=> Changes endpoints to release

Traveler/Environment/Environment.swift, Traveler/GuestAPI/GuestRoute.swift, traveler-ios-stripe/TravelerStripePaymentProvider/StripePaymentProvider.swift, traveler-swift-core/TravelerKit/TravelerRoute.swift
=> Fixes AWS endpoint url + Points endpoints to production

Traveler/Environment/Environment.swift
=> Changes environment variable name in Environment struct

Traveler.xcodeproj/xcshareddata/xcschemes/Traveler local.xcscheme, Traveler.xcodeproj/xcshareddata/xcschemes/gCrew local.xcscheme
=> Makes schemes shareable

Traveler/ViewControllers/FlightDetailsViewController.swift, Traveler/ViewControllers/FlightSearchResultViewController.swift
=> Changes departure and arrival date descriptions

traveler-swift-core/TravelerKit/Models/Category.swift
=> Fixes typo in Category Enum

traveler-swift-core/TravelerKit/Models/BookingOption.swift, traveler-swift-core/TravelerKit/Models/CatalogItemDetails.swift
=> Adds disclaimer to product detail and to options

traveler-ios-ui/TravelerKitUI/Views/CarouselViewCell.swift
=> Makes reload function in CarouselViewCell public

traveler-ios-ui/TravelerKitUI/Storyboards/CatalogItem.storyboard, traveler-ios-ui/TravelerKitUI/ViewControllers/CatalogItemResultViewController.swift
=> Hides the TOS button when there's no TOS

Traveler/AppDelegate.swift, Traveler/Storyboards/Base.lproj/Main.storyboard, Traveler/ViewControllers/MainViewController.swift, traveler-ios-ui/TravelerKitUI.xcodeproj/project.pbxproj, traveler-ios-ui/TravelerKitUI/Extensions/Facets+TravelerUI.swift, traveler-ios-ui/TravelerKitUI/Storyboards/BookingItemSearch.storyboard, traveler-ios-ui/TravelerKitUI/ViewControllers/BookingItemSearchResultViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/BookingItemSearchViewController.swift, traveler-ios-ui/TravelerKitUI/Views/CarouselItemViewCell.swift, traveler-ios-ui/TravelerKitUI/Views/CarouselItemViewCell.xib, traveler-ios-ui/TravelerKitUI/Views/CollectionHeaderView.swift, traveler-ios-ui/TravelerKitUI/Views/DoubleSlider.swift, traveler-ios-ui/TravelerKitUI/Views/DoubleSliderView.swift, traveler-ios-ui/TravelerKitUI/Views/RangeCell.swift, traveler-ios-ui/TravelerKitUI/Views/RangeCell.xib, traveler-ios-ui/TravelerKitUI/Views/ShadowedView.swift, traveler-ios-ui/TravelerKitUI/Views/Tag.swift, traveler-ios-ui/TravelerKitUI/Views/TagsCell.swift, traveler-ios-ui/TravelerKitUI/Views/TagsCell.xib, traveler-ios-ui/TravelerKitUI/Views/TagsView.swift, traveler-swift-core/TravelerKit/Models/BookingItemDetails.swift, traveler-swift-core/TravelerKit/Models/BookingItemSearchResult.swift, traveler-swift-core/TravelerKit/Models/ParkingItemDetails.swift, traveler-swift-core/TravelerKit/Models/ParkingItemSearchResult.swift, traveler-swift-core/TravelerKit/Models/ProductItemCategory.swift
=> Adds Booking Item search functionality to TravelerKitUI

traveler-swift-core/TravelerKit/Models/Coordinate.swift
=> Adds a public initializer to Coordinate model.

traveler-swift-core/TravelerKit/Models/BoundingBox.swift
=> Adds a public initializer the BoundingBox model

traveler-swift-core/TravelerKit/Models/BookingItemSearchParameters.swift
=> Modifies coding key for BookingItemSearchParameters

traveler-swift-core/TravelerKit.xcodeproj/project.pbxproj, traveler-swift-core/TravelerKit/AuthPath.swift, traveler-swift-core/TravelerKit/Delegates/SimilarProductsFetchDelegate.swift, traveler-swift-core/TravelerKit/Traveler.swift
=> Adds similar items feature to core

traveler-swift-core/TravelerKit/TravelerRoute.swift
=> Changes error code in TravelerRoute to match proper error case.

traveler-ios-ui/TravelerKitUI/ViewControllers/BookingItemSearchViewController.swift
=> Makes search bar lose focus once results are in

traveler-ios-ui/TravelerKitUI/ViewControllers/OrdersViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/WishlistViewController.swift
=> Adds references to emptySegue to show zero results

Traveler/Base.lproj/LaunchScreen.storyboard, Traveler/Storyboards/Base.lproj/AddFlight.storyboard, Traveler/Storyboards/Base.lproj/Main.storyboard, traveler-ios-ui/TravelerKitUI/ModelExtensions/Attribute+TravelerUI.swift, traveler-ios-ui/TravelerKitUI/ModelExtensions/CatalogItemDetails+TravelerUI.swift, traveler-ios-ui/TravelerKitUI/Storyboards/BookingItem.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/BookingItemSearch.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/CatalogItem.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/CatalogItemInfo.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/OrderReview.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/Orders.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/Product.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/TermsAndConditions.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/Wishlist.storyboard, traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormHeaderView.xib, traveler-ios-ui/TravelerKitUI/Views/CarouselItemViewCell.xib, traveler-ios-ui/TravelerKitUI/Views/CarouselViewCell.xib, traveler-ios-ui/TravelerKitUI/Views/FeaturedCarouselItemViewCell.xib, traveler-ios-ui/TravelerKitUI/Views/FeaturedCarouselViewCell.xib, traveler-ios-ui/TravelerKitUI/Views/HeaderView.xib, traveler-ios-ui/TravelerKitUI/Views/RangeCell.xib, traveler-ios-ui/TravelerKitUI/Views/TagsCell.xib
=> Adds dark mode support to TravelerKitUI and sample application

traveler-swift-core/TravelerKit/Models/Airport.swift, traveler-swift-core/TravelerKit/Models/Flight.swift
=> Makes Flight model conform to Codable now.

traveler-ios-ui/TravelerKitUI.xcodeproj/project.pbxproj, traveler-ios-ui/TravelerKitUI/Storyboards/BookingItem.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/SimilarItems.storyboard, traveler-ios-ui/TravelerKitUI/ViewControllers/BookingItemDetailsViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/SimilarItemsResultViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/SimilarItemsViewController.swift
=> Adds similar items feature to UI

Traveler/ViewControllers/AuthViewController.swift, traveler-swift-core/TravelerKit/Traveler.swift
=> Fixes the bug that session identity still exists after user logout.

traveler-ios-ui/TravelerKitUI/Storyboards/BookingItem.storyboard, traveler-ios-ui/TravelerKitUI/UIUtilities/HeartButton.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/BookingItemDetailsViewController.swift
=> Adds handlation when user taps wishlist button multiple times constantly.

traveler-ios-ui/TravelerKitUI/ViewControllers/BookingPassesViewController.swift, traveler-swift-core/TravelerKit/AuthPath.swift, traveler-swift-core/TravelerKit/Models/PurchaseForm.swift, traveler-swift-core/TravelerKit/Models/Question.swift, traveler-swift-core/TravelerKit/Traveler.swift
Adds implementation to save user attributes + adds implementation to pre-fill purchase form.
* Fixes #
* Connects #
=> Pre-fill forms and user attributes storing

traveler-ios-ui/TravelerKitUI/ViewControllers/BookingPassesViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/CatalogItemInfoViewController.swift, traveler-swift-core/TravelerKit.xcodeproj/project.pbxproj, traveler-swift-core/TravelerKit/AuthPath.swift, traveler-swift-core/TravelerKit/Delegates/FetchPartnerOfferingDelegate.swift, traveler-swift-core/TravelerKit/Models/AnyItem.swift, traveler-swift-core/TravelerKit/Models/BookingItemDetails.swift, traveler-swift-core/TravelerKit/Models/CatalogGroup.swift, traveler-swift-core/TravelerKit/Models/CatalogItemDetails.swift, traveler-swift-core/TravelerKit/Models/ContactInfo.swift, traveler-swift-core/TravelerKit/Models/Order.swift, traveler-swift-core/TravelerKit/Models/PartnerOffering.swift, traveler-swift-core/TravelerKit/Models/PartnerOfferingGroup.swift, traveler-swift-core/TravelerKit/Models/PartnerOfferingItem.swift, traveler-swift-core/TravelerKit/Models/PartnerOfferingsItemDetails.swift, traveler-swift-core/TravelerKit/Models/Pass.swift, traveler-swift-core/TravelerKit/Models/Product.swift, traveler-swift-core/TravelerKit/Models/ProductOffering.swift, traveler-swift-core/TravelerKit/Models/ProductType.swift, traveler-swift-core/TravelerKit/Models/PurchaseForm.swift, traveler-swift-core/TravelerKit/Models/PurchaseFormFetchingError.swift, traveler-swift-core/TravelerKit/Models/WishlistResult.swift, traveler-swift-core/TravelerKit/Traveler.swift
…ffering" to which passes and partner offerings conform to + Refactors purchase form fetch method to support new protocol
* Fixes #
* Connects #
=> PartnerOfferings Core 

Traveler.xcodeproj/project.pbxproj, Traveler/AppDelegate.swift, Traveler/ViewControllers/FlightSearchViewController.swift, traveler-ios-ui/TravelerKitUI.xcodeproj/project.pbxproj, traveler-ios-ui/TravelerKitUI/ModelExtensions/PartnerOffering+TravelerUI.swift, traveler-ios-ui/TravelerKitUI/Storyboards/BookingItem.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/CatalogItem.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/Error.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/OrderReview.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/PartnerOffering.storyboard, traveler-ios-ui/TravelerKitUI/ViewControllers/BookingItemQueryViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/CatalogItemDetailsViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/ErrorViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/OfferingsDisplayViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/OfferingsSelectViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/OrderSummaryViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/PartnerOfferingDetailsViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/PartnerOfferingQuantityViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/PartnerOfferingsFetchViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/ProductItemViewController.swift, traveler-ios-ui/TravelerKitUI/Views/ExpandingCell.swift, traveler-swift-core/TravelerKit/Models/Product.swift
=> PartnerOfferings UI

traveler-swift-core/TravelerKit.xcodeproj/project.pbxproj, traveler-swift-core/TravelerKit/Models/Catalog.swift, traveler-swift-core/TravelerKit/Models/CatalogGroup.swift, traveler-swift-core/TravelerKit/Models/Itinerary/ItineraryResult.swift, traveler-swift-core/TravelerKit/Models/LossyDecodableArray.swift, traveler-swift-core/TravelerKit/Models/WishlistResult.swift
=> Futureproofs against backend changes for static types

traveler-ios-ui/TravelerKitUI/Storyboards/Orders.storyboard
=> Fixes the bug that the cancellation items are selectable.

traveler-ios-ui/TravelerKitUI/Storyboards/Parking.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/PurchasedProduct.storyboard, traveler-ios-ui/TravelerKitUI/ViewControllers/Parking/ParkingItemDetailsPriceViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/Parking/ParkingQueryViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/Parking/ParkingResultListViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/Parking/ParkingResultMapListController.swift, traveler-ios-ui/TravelerKitUI/Views/LabeledAnnotationView.swift, traveler-swift-core/TravelerKit/Models/Price.swift, traveler-swift-core/TravelerKit/Models/Product/Purchasable/BookingItem.swift
=> Makes some other polishing changes to parking.

traveler-ios-ui/TravelerKitUI/ModelExtensions/BookingOption+TravelerUI.swift, traveler-ios-ui/TravelerKitUI/Storyboards/BookingItem.storyboard, traveler-ios-ui/TravelerKitUI/Storyboards/Wishlist.storyboard, traveler-ios-ui/TravelerKitUI/ViewControllers/AvailabilityViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/BookingOptionsViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/WishlistResultViewController.swift, traveler-ios-ui/TravelerKitUI/Views/CarouselItemViewCell.xib, traveler-ios-ui/TravelerKitUI/Views/InfoCell.swift, traveler-swift-core/TravelerKit/Models/Product/Purchasable/BookingItem.swift.orig
Fixes wrong implementation of shadowed view for wishlist + Adds width calculation for wishlist cells + enhances existing dark mode support + add better dark mode support for parking + removes `BookableDetailsViewController` as it's no longer used
* Fixes #
* Connects #
=> Dark mode for parking and other enhancements

traveler-swift-core/TravelerKit/Models/QueryType.swift
=> Makes QueryType public

traveler-ios-ui/TravelerKitUI/ViewControllers/ItineraryViewController.swift
=> Makes reload and filter functions public in ItineraryViewController

traveler-ios-ui/TravelerKitUI/ViewControllers/ItineraryViewController.swift
=> Adds reset filters functionality to ItineraryViewController

traveler-ios-ui/TravelerKitUI/ModelExtensions/Order+TravelerUI.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/OrderResultViewController.swift, traveler-swift-core/TravelerKit/Models/Order.swift
=> Adds logic to handle unknown orders in TravelerKit and TravelerKitUI

traveler-ios-ui/TravelerKitUI/UIUtilities/FormView/FormView.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/PurchaseQuestionsViewController.swift, traveler-swift-core/TravelerKit/Models/PurchaseForm.swift, traveler-swift-core/TravelerKit/Models/Question.swift, traveler-swift-core/TravelerKit/Models/ValidationError.swift, traveler-swift-core/TravelerKit/Models/ValidationRule.swift
=> Adds support for regex validation rules in purchase form

traveler-ios-ui/TravelerKitUI/ViewControllers/AvailabilityViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/CatalogItemViewController.swift, traveler-ios-ui/TravelerKitUI/ViewControllers/PaymentConfirmationViewController.swift, traveler-swift-core/TravelerKit.xcodeproj/project.pbxproj, traveler-swift-core/TravelerKit/Extensions/LocalizedError+Description.swift, traveler-swift-core/TravelerKit/Models/BookingError.swift, traveler-swift-core/TravelerKit/Models/CancellationError.swift, traveler-swift-core/TravelerKit/Models/PaymentError.swift, traveler-swift-core/TravelerKit/Models/UnhandledError.swift, traveler-swift-core/TravelerKit/Pineapple/NetworkError.swift, traveler-swift-core/TravelerKit/TravelerRoute.swift
Shows trace ID with localized error message.
* Fixes #
* Connects #
=> Shows trace ID with localized error message

traveler-swift-core/TravelerKit/Models/PurchaseForm.swift
=> Modifies logic in PurchaseForm validation to accept empty strings

traveler-swift-core/TravelerKit/AuthPath.swift, traveler-swift-core/TravelerKit/Models/CatalogQuery.swift
=> Adds support to fetch the catalog based on city in CatalogQuery

traveler-swift-core/TravelerKit/AuthPath.swift
Dynamic categories URL was wrong. This PR fixes that.
* Fixes #
* Connects #
=> Replaces wrong dynamic categories URL with the correct one

traveler-swift-core/TravelerKit/AuthPath.swift
Replaces deprecated /order endpoint with the correct one traveler/{id}/order
* Fixes #
* Connects #
=> Replaces deprecated orders endpoint with the correct one

traveler-ios-ui/TravelerKitUI/ViewControllers/BookingItemSearch/BookingItemSearchResultViewController.swift, traveler-swift-core/TravelerKit.xcodeproj/project.pbxproj, traveler-swift-core/TravelerKit/AuthPath.swift, traveler-swift-core/TravelerKit/Models/BookingItemSearchFilters.swift, traveler-swift-core/TravelerKit/Models/BookingItemSearchParameters.swift, traveler-swift-core/TravelerKit/Models/DateRangeFilter.swift, traveler-swift-core/TravelerKit/Models/Queries/BookingItemQuery.swift
Makes changes to BookingItemQuery and related BookingItemSearchFilters and BookingItemSearchParameters to add date range support.
* Fixes #
* Connects #
=> Date Range Filter

traveler-swift-core/TravelerKit/AuthPath.swift
https://guestlogix.atlassian.net/browse/WLA-509
Backend expects the date format to be ISO8601.
* Fixes #
* Connects #
=> Changes the format of dates sent to booking item search.

traveler-swift-core/TravelerKit.xcodeproj/project.pbxproj, traveler-swift-core/TravelerKit/Models/BookingItemSearchParameters.swift, traveler-swift-core/TravelerKit/Models/CatalogGroup.swift, traveler-swift-core/TravelerKit/Models/Queries/AnyQuery.swift
https://guestlogix.atlassian.net/browse/SDK-26
Adds AnyQuery to GroupItem. AnyQuery is used to search for all items in that group.
Dependency for WLA-532 
https://guestlogix.atlassian.net/browse/WLA-532
* Fixes #
* Connects #
=> SDK-26-groups_search_query
